DEFAULT_DATA = {
    # Buttons

    'RotateButtonDisplay': 'both',  # 或者 'icon' 或者 'text'
    'RotateButtonIconHover': './rope/media/001.png',  # 替换成你的旋转图标路径
    'RotateButtonIconOff': './rope/media/002.png',  # 替换成你的旋转图标路径
    'RotateButtonIconOn': './rope/media/002.png',  # 替换成你的旋转图标路径
    'RotateButtonInfoText': '旋转画面:\n将摄像头获取的画面旋转90度。',
    'RotateButtonState': False,
    'RotateDisplay': 'both',  # Add this line
    'RotateIconOn': './rope/media/rec_on.png',
    'RotateIconOff': './rope/media/rec_on.png',  # Add this line
    'RotateIconHover': './rope/media/rec_on.png',
    'RotateText': './rope/media/rec_on.png',
    'RotateState': './rope/media/rec_on.png',
    'RotateButtonText': '旋转',
    #眼睛
    'EyeParserSwitchState': False,
    'EyeParserSliderAmount': 0,
    'EyeParserSliderMin': -50,
    'EyeParserSliderMax': 50,
    'EyeParserSliderInc': 0.5,
    'EyeParserSliderInfoText': '眼睛蒙版数量:\n调整蒙版的大小。负值只遮挡眼睛内部，正值还包括眼睑。',

    # 开关
    'SkinParserSwitchState': False,
    'BrowParserSwitchState': False,
    'NoseParserSwitchState': False,
    'NeckParserSwitchState': False,
    'ClothParserSwitchState': False,
    'HairParserSwitchState': False,
    'HatParserSwitchState': False,

    # 滑块
    'SkinParserSliderAmount': 0,
    'SkinParserSliderInc': 0.5,
    'SkinParserSliderMin': -50,
    'SkinParserSliderMax': 50,
    'SkinParserSliderInfoText': '皮肤蒙版数量:\n调整蒙版的大小。',

    'BrowParserSliderAmount': 0,
    'BrowParserSliderInc': 0.5,
    'BrowParserSliderMin': -50,
    'BrowParserSliderMax': 50,
    'BrowParserSliderInfoText': '眉毛蒙版数量:\n调整蒙版的大小。',

    'NoseParserSliderAmount': 0,
    'NoseParserSliderInc': 0.5,
    'NoseParserSliderMin': -50,
    'NoseParserSliderMax': 50,
    'NoseParserSliderInfoText': '鼻子蒙版数量:\n调整蒙版的大小。',

    'NeckParserSliderAmount': 0,
    'NeckParserSliderInc': 0.5,
    'NeckParserSliderMin': -50,
    'NeckParserSliderMax': 50,
    'NeckParserSliderInfoText': '脖子蒙版数量:\n调整蒙版的大小。',

    'ClothParserSliderAmount': 0,
    'ClothParserSliderInc': 0.5,
    'ClothParserSliderMin': -50,
    'ClothParserSliderMax': 50,
    'ClothParserSliderInfoText': '衣服蒙版数量:\n调整蒙版的大小。',

    'HairParserSliderAmount': 0,
    'HairParserSliderInc': 0.5,
    'HairParserSliderMin': -50,
    'HairParserSliderMax': 50,
    'HairParserSliderInfoText': '头发蒙版数量:\n调整蒙版的大小。',

    'HatParserSliderAmount': 0,
    'HatParserSliderInc': 0.5,
    'HatParserSliderMin': -50,
    'HatParserSliderMax': 50,
    'HatParserSliderInfoText': '帽子蒙版数量:\n调整蒙版的大小。',

    #直播分辨率
    'CameraResolutionTextSelModes': ['3840x2160','2560x1400','1920x1080', '1280x720', '720x480', '640x480', '320x240'],
    'CameraResolutionTextSelMode': '1920x1080',  # 添加默认摄像头分辨率
    'CameraResolutionTextSelInfoText': '启用后，可以选择自定义的摄像头分辨率。',
    'CameraEnabledState': False,  # 添加 CameraEnabledState 键
    'CameraEnabledInfoText': '启用摄像头输入的分辨率设置，默认关闭。',

    'preview_column': '',
    'LiveInfoText': '启动直播流。',

    'LiveState': False,
    'LiveText': '直播',
    'LiveDisplay': 'text',  # 添加 LiveDisplay 键，并设置其值为 'text'

    'AddMarkerButtonDisplay': 'icon',
    'AddMarkerButtonIconHover': './rope/media/add_marker_hover.png',
    'AddMarkerButtonIconOff': './rope/media/add_marker_off.png',
    'AddMarkerButtonIconOn': './rope/media/add_marker_off.png',
    'AddMarkerButtonInfoText': '添加标记:\n将参数标记附加到当前帧。标记会复制所有参数设置并将其应用于所有后续帧，或者直到遇到另一个标记。',
    'AddMarkerButtonState': False,
    'AudioDisplay': 'text',
    'AudioInfoText': '启用实时音频:\n在预览播放期间添加来自输入视频的音频。如果您无法保持输入视频帧速率，音频将延迟。',
    'AudioState': False,
    'AudioText': '启用音频',
    'AutoSwapState': False,
    'ClearFacesDisplay': 'text',
    'ClearFacesIcon': './rope/media/tarfacedel.png',
    'ClearFacesIconHover': './rope/media/rec.png',
    'ClearFacesIconOff': './rope/media/rec.png',
    'ClearFacesIconOn': './rope/media/rec.png',
    'ClearFacesInfoText': '删除面部:\n删除所有当前发现的面部。',
    'ClearFacesState': False,
    'ClearFacesText': '清除面部',
    'ClearmemState': False,
    'DefaultParamsButtonDisplay': 'text',
    'DefaultParamsButtonInfoText': '加载默认参数:\n加载此列的 Rope 默认参数。',
    'DefaultParamsButtonState': False,
    'DefaultParamsButtonText': '加载默认值',
    'DelEmbedDisplay': 'text',
    'DelEmbedIconHover': './rope/media/rec.png',
    'DelEmbedIconOff': './rope/media/rec.png',
    'DelEmbedIconOn': './rope/media/rec.png',
    'DelEmbedInfoText': '删除嵌入:\n删除当前选定的嵌入。',
    'DelEmbedState': False,
    'DelEmbedText': '删除嵌入',
    'DelMarkerButtonDisplay': 'icon',
    'DelMarkerButtonIconHover': './rope/media/remove_marker_hover.png',
    'DelMarkerButtonIconOff': './rope/media/remove_marker_off.png',
    'DelMarkerButtonIconOn': './rope/media/remove_marker_off.png',
    'DelMarkerButtonInfoText': '删除标记:\n从当前帧删除参数标记。',
    'DelMarkerButtonState': False,
    'FindFacesDisplay': 'text',
    'FindFacesIcon': './rope/media/tarface.png',
    'FindFacesIconHover': './rope/media/rec.png',
    'FindFacesIconOff': './rope/media/rec.png',
    'FindFacesIconOn': './rope/media/rec.png',
    'FindFacesInfoText': '查找面部:\n在当前帧中查找所有新面部。',
    'FindFacesState': False,
    'FindFacesText': '查找面部',
    'ImgDockState': False,
    'ImgVidMode': '视频',
    'ImgVidState': False,
    'LoadParamsButtonDisplay': 'text',
    'LoadParamsButtonInfoText': '加载保存的参数:\n如果之前保存了该列的所有参数，则加载它们。',
    'LoadParamsButtonState': False,
    'LoadParamsButtonText': '加载参数',
    'LoadSFacesDisplay': 'both',
    'LoadSFacesIcon': './rope/media/save.png',
    'LoadSFacesIconHover': './rope/media/save.png',
    'LoadSFacesIconOff': './rope/media/save.png',
    'LoadSFacesIconOn': './rope/media/save.png',
    'LoadSFacesInfoText': '选择源面部文件夹:\n从文件夹中选择并加载源面部。确保文件夹中只包含<好>图像。',
    'LoadSFacesState': False,
    'LoadSFacesText': '选择面部文件夹',
    'LoadTVideosDisplay': 'both',
    'LoadTVideosIconHover': './rope/media/save.png',
    'LoadTVideosIconOff': './rope/media/save.png',
    'LoadTVideosIconOn': './rope/media/save.png',
    'LoadTVideosInfoText': '选择输入视频/图像文件夹:\n从文件夹中选择并加载媒体。',
    'LoadTVideosState': False,
    'LoadTVideosText': '选择视频文件夹',
    'MaskViewDisplay': 'text',
    'MaskViewInfoText': '显示蒙版:\n并排显示面部的蒙版。有助于了解蒙版行为和结果。',
    'MaskViewState': False,
    'MaskViewText': '显示蒙版',
    'NextMarkerButtonDisplay': 'icon',
    'NextMarkerButtonIconHover': './rope/media/next_marker_hover.png',
    'NextMarkerButtonIconOff': './rope/media/next_marker_off.png',
    'NextMarkerButtonIconOn': './rope/media/next_marker_off.png',
    'NextMarkerButtonInfoText': '下一个标记:\n移动到下一个标记。',
    'NextMarkerButtonState': False,
    'OutputFolderDisplay': 'both',
    'OutputFolderIconHover': './rope/media/save.png',
    'OutputFolderIconOff': './rope/media/save.png',
    'OutputFolderIconOn': './rope/media/save.png',
    'OutputFolderInfoText': '选择保存文件夹:\n选择保存视频和图像的文件夹。',
    'OutputFolderState': False,
    'OutputFolderText': '选择输出文件夹',
    'PerfTestState': False,
    'PlayDisplay': 'icon',
    'PlayIconHover': './rope/media/play_hover.png',
    'PlayIconOff': './rope/media/play_off.png',
    'PlayIconOn': './rope/media/play_on.png',
    'PlayInfoText': '播放:\n播放视频。再次按下停止播放',
    'PlayState': False,
    'PrevMarkerButtonDisplay': 'icon',
    'PrevMarkerButtonIconHover': './rope/media/previous_marker_hover.png',
    'PrevMarkerButtonIconOff': './rope/media/previous_marker_off.png',
    'PrevMarkerButtonIconOn': './rope/media/previous_marker_off.png',
    'PrevMarkerButtonInfoText': '上一个标记:\n移动到上一个标记。',
    'PrevMarkerButtonState': False,
    'RecordDisplay': 'icon',
    'RecordIconHover': './rope/media/rec_hover.png',
    'RecordIconOff': './rope/media/rec_off.png',
    'RecordIconOn': './rope/media/rec_on.png',
    'RecordInfoText': '录制:\n为录制武装 PLAY 按钮。按下录制，然后播放开始录制。再次按下播放停止录制。',
    'RecordState': False,
    'SaveImageState': False,
    'SaveParamsButtonDisplay': 'text',
    'SaveParamsButtonInfoText': '保存参数:\n保存此列中的所有参数。',
    'SaveParamsButtonState': False,
    'SaveParamsButtonText': '保存参数',
    'StartRopeDisplay': 'both',
    'StartRopeIconHover': './rope/media/rope.png',
    'StartRopeIconOff': './rope/media/rope.png',
    'StartRopeIconOn': './rope/media/rope.png',
    'StartRopeInfoText': '启动 Rope:\n启动 Rope 应用程序。',
    'StartRopeState': False,
    'StartRopeText': '刷新列表',
    'SwapFacesDisplay': 'text',
    'SwapFacesInfoText': '交换:\n交换分配的源面部和目标面部。',
    'SwapFacesState': False,
    'SwapFacesText': '换脸',
    'TLBeginningDisplay': 'icon',
    'TLBeginningIconHover': './rope/media/tl_beg_hover.png',
    'TLBeginningIconOff': './rope/media/tl_beg_off.png',
    'TLBeginningIconOn': './rope/media/tl_beg_on.png',
    'TLBeginningInfoText': '时间线开始:\n将时间线句柄移动到第一帧。',
    'TLBeginningState': False,
    'TLLeftDisplay': 'icon',
    'TLLeftIconHover': './rope/media/tl_left_hover.png',
    'TLLeftIconOff': './rope/media/tl_left_off.png',
    'TLLeftIconOn': './rope/media/tl_left_on.png',
    'TLLeftInfoText': '时间线向左移动:\n将时间线句柄向左移动 30 帧。',
    'TLLeftState': False,
    'TLRightDisplay': 'icon',
    'TLRightIconHover': './rope/media/tl_right_hover.png',
    'TLRightIconOff': './rope/media/tl_right_off.png',
    'TLRightIconOn': './rope/media/tl_right_on.png',
    'TLRightInfoText': '时间线向右移动:\n将时间线句柄向右移动 30 帧。',
    'TLRightState': False,

    'SaveImageButtonDisplay': 'text',
    'SaveImageButtonInfoText': '保存图像:\n将当前图像保存到您的输出文件夹。',
    'SaveImageButtonState': False,
    'SaveImageButtonText': '保存图像',

    'AutoSwapButtonDisplay': 'text',
    'AutoSwapButtonInfoText': '自动交换:\n自动将您当前选定的输入面部应用于新图像。',
    'AutoSwapButtonState': False,
    'AutoSwapButtonText': '自动交换',

    'ClearVramButtonDisplay': 'text',
    'ClearVramButtonInfoText': '清除 VRAM:\n从 VRAM 中清除模型。',
    'ClearVramButtonState': False,
    'ClearVramButtonText': '清除 VRAM',

    'GetNewEmbButtonDisplay': 'text',
    'GetNewEmbButtonInfoText': '清除 VRAM:\n从 VRAM 中清除模型。',
    'GetNewEmbButtonState': False,
    'GetNewEmbButtonText': '清除 VRAM',

    'StopMarkerButtonnDisplay': 'icon',
    'StopMarkerButtonIconHover': './rope/media/previous_marker_hover.png',
    'StopMarkerButtonIconOff': './rope/media/previous_marker_off.png',
    'StopMarkerButtonIconOn': './rope/media/previous_marker_off.png',
    'StopMarkerButtonInfoText': '清除 VRAM:\n从 VRAM 中清除模型。',
    'StopMarkerButtonState': False,
    'StopMarkerButtonText': '清除 VRAM',

    # 开关
    'ColorSwitchInfoText': 'RGB 调整:\n微调交换的 RGB 颜色值。',
    'ColorSwitchState': False,
    'DiffSwitchInfoText': '差异器:\n当两个图像之间的差异很小时，允许一些原始面部显示在交换结果中。可以帮助将一些纹理带回到交换的面部。',
    'DiffSwitchState': False,
    'FaceAdjSwitchInfoText': 'KPS 和缩放调整:\n这是一个实验性功能，用于对检测器找到的面部地标进行直接调整。还有一个选项可以调整交换面部的比例。',
    'FaceAdjSwitchState': False,
    'FaceParserSwitchInfoText': '背景蒙版:\n允许原始图像的未处理背景显示在最终交换中。',
    'FaceParserSwitchState': False,
    'MouthParserSwitchInfoText': '嘴部蒙版:\n允许原始面部的嘴部显示在交换面部上。',
    'MouthParserSwitchState': False,
    'OccluderSwitchInfoText': '遮挡蒙版:\n允许遮挡面部的对象显示在交换图像中。',
    'OccluderSwitchState': False,
    'OrientSwitchInfoText': '方向:\n旋转面部检测器以更好地检测不同角度的面部。',
    'OrientSwitchState': False,
    'RestorerSwitchInfoText': '面部修复器:\n通过上采样修复交换图像。',
    'RestorerSwitchState': False,
    'StrengthSwitchInfoText': '交换器强度:\n应用额外的交换迭代以增加结果的强度，这可能会增加相似性',
    'StrengthSwitchState': False,
    'CLIPSwitchInfoText': '文本蒙版:\n使用描述来识别最终交换图像中将存在于的对象。',
    'CLIPSwitchState': False,

    # 滑块

    'BlendSliderAmount': 5,
    'BlendSliderInc': 1,
    'BlendSliderInfoText': '混合:\n组合蒙版混合距离。不应用于边界蒙版。',
    'BlendSliderMax': 100,
    'BlendSliderMin': 0,
    'BorderBlurSliderAmount': 10,
    'BorderBlurSliderInc': 1,
    'BorderBlurSliderInfoText': '边界蒙版混合:\n边界蒙版混合距离。',
    'BorderBlurSliderMax': 64,
    'BorderBlurSliderMin': 0,
    'BorderBottomSliderAmount': 10,
    'BorderBottomSliderInc': 1,
    'BorderBottomSliderInfoText': '底部边界距离:\n一个具有可调整顶部、底部和侧面的矩形，它将交换面部结果混合回原始图像。',
    'BorderBottomSliderMax': 64,
    'BorderBottomSliderMin': 0,
    'BorderSidesSliderAmount': 10,
    'BorderSidesSliderInc': 1,
    'BorderSidesSliderInfoText': '侧面边界距离:\n一个具有可调整顶部、底部和侧面的矩形，它将交换面部结果混合回原始图像。',
    'BorderSidesSliderMax': 64,
    'BorderSidesSliderMin': 0,
    'BorderTopSliderAmount': 10,
    'BorderTopSliderInc': 1,
    'BorderTopSliderInfoText': '顶部边界距离:\n一个具有可调整顶部、底部和侧面的矩形，它将交换面部结果混合回原始图像。',
    'BorderTopSliderMax': 64,
    'BorderTopSliderMin': 0,
    'ColorBlueSliderAmount': 0,
    'ColorBlueSliderInc': 1,
    'ColorBlueSliderInfoText': 'RGB 蓝色调整',
    'ColorBlueSliderMax': 100,
    'ColorBlueSliderMin': -100,
    'ColorGreenSliderAmount': 0,
    'ColorGreenSliderInc': 1,
    'ColorGreenSliderInfoText': 'RGB 绿色调整',
    'ColorGreenSliderMax': 100,
    'ColorGreenSliderMin': -100,
    'ColorRedSliderAmount': 0,
    'ColorRedSliderInc': 1,
    'ColorRedSliderInfoText': 'RGB 红色调整',
    'ColorRedSliderMax': 100,
    'ColorRedSliderMin': -100,
    'DetectScoreSliderAmount': 50,
    'DetectScoreSliderInc': 1,
    'DetectScoreSliderInfoText': '检测分数限制:\n确定检测面部所需的最低分数。更高的值需要更高质量的面部。例如，如果面部在极端角度时闪烁，则提高此值将限制交换尝试。',
    'DetectScoreSliderMax': 100,
    'DetectScoreSliderMin': 1,
    'DiffSliderAmount': 4,
    'DiffSliderInc': 1,
    'DiffSliderInfoText': '差异化数量:\n更高的值会放宽相似性约束。',
    'DiffSliderMax': 100,
    'DiffSliderMin': 0,
    'FaceParserSliderAmount': 0,
    'FaceParserSliderInc': 0.5,
    'FaceParserSliderInfoText': '背景蒙版数量:\n负/正值缩小和扩大蒙版。',
    'FaceParserSliderMax': 50,
    'FaceParserSliderMin': -50,
    'FaceScaleSliderAmount': 0,
    'FaceScaleSliderInc': 1,
    'FaceScaleSliderInfoText': '面部缩放数量',
    'FaceScaleSliderMax': 20,
    'FaceScaleSliderMin': -20,
    'KPSScaleSliderAmount': 0,
    'KPSScaleSliderInc': 1,
    'KPSScaleSliderInfoText': 'KPS 缩放数量:\n扩大和缩小检测点距离。',
    'KPSScaleSliderMax': 100,
    'KPSScaleSliderMin': -100,
    'KPSXSliderAmount': 0,
    'KPSXSliderInc': 1,
    'KPSXSliderInfoText': 'KPS X 方向数量:\n左右移动检测点',
    'KPSXSliderMax': 100,
    'KPSXSliderMin': -100,
    'KPSYSliderAmount': 0,
    'KPSYSliderInc': 1,
    'KPSYSliderInfoText': 'KPS Y 方向数量:\n上下移动检测点',
    'KPSYSliderMax': 100,
    'KPSYSliderMin': -100,
    'MouthParserSliderAmount': 0,
    'MouthParserSliderInc': 0.5,
    'MouthParserSliderInfoText': '嘴部蒙版数量:\n调整蒙版的大小。负值只遮挡嘴巴内部，包括舌头。正值还包括嘴唇。',
    'MouthParserSliderMax': 50,
    'MouthParserSliderMin': -50,
    'OccluderSliderAmount': 0,
    'OccluderSliderInc': 1,
    'OccluderSliderInfoText': '遮挡器数量:\n扩大或缩小遮挡区域',
    'OccluderSliderMax': 100,
    'OccluderSliderMin': -100,
    'OrientSliderAmount': 0,
    'OrientSliderInc': 90,
    'OrientSliderInfoText': '方向角度:\n将其设置为输入面部角度的角度以帮助进行躺下/倒置/等。角度按顺时针方向读取。',
    'OrientSliderMax': 270,
    'OrientSliderMin': 0,
    'RestorerSliderAmount': 100,
    'RestorerSliderInc': 5,
    'RestorerSliderInfoText': '修复器数量:\n将修复结果混合回原始交换。',
    'RestorerSliderMax': 100,
    'RestorerSliderMin': 0,
    'StrengthSliderAmount': 100,
    'StrengthSliderInc': 25,
    'StrengthSliderInfoText': '强度数量:\n增加最多 5 倍的额外交换 (500%)。200% 通常是一个很好的结果。设置为 0 以关闭交换，但允许其余管道应用于原始图像。',
    'StrengthSliderMax': 500,
    'StrengthSliderMin': 0,
    'ThreadsSliderAmount': 2,
    'ThreadsSliderInc': 1,
    'ThreadsSliderInfoText': '执行线程:\n设置播放和录制时的执行线程数。很大程度上取决于 GPU VRAM。24GB 为 5 个线程。',
    'ThreadsSliderMax': 20,
    'ThreadsSliderMin': 1,
    'ThresholdSliderAmount': 55,
    'ThresholdSliderInc': 1,
    'ThresholdSliderInfoText': '阈值数量:\n提高以减少交换多人时面部跳动。更高的值更严格。',
    'ThresholdSliderMax': 100,
    'ThresholdSliderMin': 0,
    'VideoQualSliderAmount': 18,
    'VideoQualSliderInc': 1,
    'VideoQualSliderInfoText': '视频质量:\n录制视频的编码质量。0 最佳，50 最差，18 几乎无损。文件大小随着质量数字的降低而增加。',
    'VideoQualSliderMax': 50,
    'VideoQualSliderMin': 0,

    'CLIPSliderAmount': 50,
    'CLIPSliderInc': 1,
    'CLIPSliderInfoText': '文本蒙版强度:\n增加以加强效果。',
    'CLIPSliderMax': 100,
    'CLIPSliderMin': 0,

    'ColorGammaSliderAmount': 1,
    'ColorGammaSliderInc': 0.02,
    'ColorGammaSliderInfoText': '伽马值:\n更改伽马。',
    'ColorGammaSliderMax': 2,
    'ColorGammaSliderMin': 0,

    # 文本选择
    'DetectTypeTextSelInfoText': '面部检测模型:\n选择面部检测模型。大多数情况下只有细微的差别，但在面部处于极端角度或被遮挡时，可能会出现显着差异。',
    'DetectTypeTextSelMode': 'Retinaface',
    'DetectTypeTextSelModes': ['Retinaface', 'Yolov8', 'SCRDF'],
    'PreviewModeTextSelInfoText': '',
    'PreviewModeTextSelMode': 'Video',
    'PreviewModeTextSelModes': ['Video', 'Image','Theater'],
    'RecordTypeTextSelInfoText': '视频录制库:\n选择用于视频录制的录制库。FFMPEG 使用视频质量滑块来调整最终视频的大小和质量。OPENCV 没有选项，但速度更快，并产生良好的结果。',
    'RecordTypeTextSelMode': 'FFMPEG',
    'RecordTypeTextSelModes': ['FFMPEG', 'OPENCV'],
    'RestorerDetTypeTextSelInfoText': '对齐:\n选择面部如何对齐进行修复。原始保留面部特征和表情，但可能会显示一些伪影。参考会柔化特征。混合更接近参考，但速度快得多。',
    'RestorerDetTypeTextSelMode': 'Blend',
    'RestorerDetTypeTextSelModes': ['Original', 'Blend', 'Reference'],
    'RestorerTypeTextSelInfoText': '修复器类型:\n选择修复器类型。\n速度：gpen256>gfpgan>codeformer>gpen512...',
    'RestorerTypeTextSelMode': 'gpen_bfr_256',
    'RestorerTypeTextSelModes': ['codeformer_fp16_512', 'gfpgan_1.2_512', 'gfpgan_1.3_512', 'gfpgan_1.4_512', 'gpen_bfr_256', 'gpen_bfr_512', 'gpen_bfr_1024', 'gpen_bfr_2048'],
    'MergeTextSelInfoText': '输入面部合并数学:\n当 shift-点击面部进行合并时，确定如何组合嵌入向量。',
    'MergeTextSelMode': 'Mean',
    'MergeTextSelModes': ['Mean', 'Median'],
    'SwapperTypeTextSelInfoText': '交换器输出分辨率:\n确定交换器输出的分辨率。',
    'SwapperTypeTextSelMode': '128',
    'SwapperTypeTextSelModes': ['128', '256', 'simswap_512'],


    # 文本输入
    'CLIPTextEntry': '',
    'CLIPTextEntryInfoText': '文本蒙版输入:\n要使用，请在方框中键入用逗号分隔的单词，然后按<enter>。',
}

PARAM_VARS = {

    'CLIPState': False,
    'CLIPMode': 0,
    'CLIPModes': ['CLIP'],
    'CLIPAmount': [50],
    'CLIPMin': 0,
    'CLIPMax': 100,
    'CLIPInc': 1,
    'CLIPUnit': '%',
    'CLIPIcon': './rope/media/CLIP.png',
    'CLIPMessage': 'CLIP - 基于文本的遮挡器。被遮挡的对象在最终图像中可见（从蒙版中遮挡）。[LB: 开/关，MW: 强度]',
    'CLIPFunction': False,

    "CLIPText": '',
}

PARAMS = {

    'ClearmemFunction': 'self.clear_mem()',
    'PerfTestFunction': 'self.toggle_perf_test()',
    'ImgVidFunction': 'self.toggle_vid_img()',
    'AutoSwapFunction': 'self.toggle_auto_swap()',
    'SaveImageFunction': 'self.save_image()',

    'ClearmemIcon': './rope/media/clear_mem.png',
    'SaveImageIcon': './rope/media/save_disk.png',
    'PerfTestIcon': './rope/media/test.png',
    'RefDelIcon': './rope/media/construction.png',
    'TransformIcon': './rope/media/scale.png',
    'ThresholdIcon': './rope/media/thresh.png',
    'LoadSFacesIcon': './rope/media/save.png',
    'BorderIcon': './rope/media/maskup.png',
    'OccluderIcon': './rope/media/occluder.png',
    'ColorIcon': './rope/media/rgb.png',
    'StrengthIcon': './rope/media/strength.png',
    'OrientationIcon': './rope/media/orient.png',
    'DiffIcon': './rope/media/diff.png',
    'MouthParserIcon': './rope/media/parse.png',
    'AudioIcon': './rope/media/rgb.png',
    'VideoQualityIcon': './rope/media/tarface.png',
    'MaskViewIcon': './rope/media/maskblur.png',
    'BlurIcon': './rope/media/blur.png',
    'ToggleStopIcon': './rope/media/STOP.png',
    'DelEmbedIcon': './rope/media/delemb.png',
    'ImgVidIcon': './rope/media/imgvid.png',

    'ImgVidMessage': '图像/视频 - 在图像和视频文件夹视图之间切换。',
    'ToggleStopMessage': '停止标记 - 设置一个将停止视频播放/录制的帧。',
    'AutoSwapMessage': '自动交换 - 自动将图像中的第一个人交换到选择的源面部 [LB: 打开/关闭]',
    'SaveImageMessage': '保存图像 - 将图像保存到输出文件夹',
    'ClearmemMessage': '清除 VRAM - 从 VRAM 中清除所有模型 [LB: 清除]',
    'PerfTestMessage': '性能数据 - 在控制台中显示关键 Rope 功能的计时数据。[LB: 打开/关闭]',
    'RefDelMessage': '参考增量 - 修改参考点。打开蒙版预览以查看调整。[LB: 打开/关闭，RB: 平移 x/y，并缩放，MW: 数量]',
    'ThresholdMessage': '阈值 - 用于确定目标面部是否与帧中的面部匹配的阈值。越低越严格。[LB: 使用数量/匹配所有，MW: 值]',
    'TransformMessage': '缩放 - 调整面部的缩放比例。与背景解析器一起使用以混合到图像中。[LB: 打开/关闭，MW: 数量]',
    'PlayMessage': '播放 - 播放视频。再次按下停止播放',

}